language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsqlite3-dev
      - libgtest-dev
      - g++-4.8

before_script:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar -xf /tmp/cmake.tar.gz
  - export CMAKE=$PWD/cmake-3.2.3-Linux-x86_64/bin/cmake
  - mkdir gtest && cd gtest
  - cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest/
  - make
  - export GTEST_ROOT=$PWD
  - cd ..

script:
  - mkdir bin && cd bin
  - $CMAKE .. && make && make test 
  - make check
