language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsqlite3-dev
      - libgtest-dev

before_script:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar -xvf /tmp/cmake.tar.gz
  - export PATH=$PATH:$PWD/cmake-3.2.3-Linux-x86_64/bin/

script:
  - mkdir bin && cd bin
  - cmake ..
  - make
  - make test 
  - make check
