language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsqlite3-dev
      - libgtest-dev

script:
  - mkdir bin && cd bin
  - cmake ..
  - make
  - make test
  - make check
